# Site settings
title: Classical Music Composition Using Hidden Markov Models
email: anna.yanchenko@duke.edu
description: > # this means to ignore newlines until "baseurl:"
  Supplementary materials and accompanying site for "Classical Music Composition Using Hidden Markov Models".
baseurl: "https://aky4wn.github.io/Classical-Music-Composition-Using-State-Space-Models" # the subpath of your site, e.g. /blog/
url: " https://aky4wn.github.io/Classical-Music-Composition-Using-State-Space-Models" # the base hostname & protocol for your site
github_username:  aky4wn

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
